#!/bin/bash

for filename in ~aycock/411/TEST/ms1/scan.t*; do
	out="$(basename $filename)"
	printf "input:\n" > $out
	cat $filename >> $out
	printf "\n\noutput:\n" >> $out
	~aycock/411/TEST/reference/golf $filename >> $out 2>&1
done

